# Generated by Django 5.2.6 on 2025-09-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='აქტიურია'),
        ),
    ]
