# Generated by Django 5.2.6 on 2025-09-19 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_create_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['title'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
