# Generated by Django 5.2.6 on 2025-09-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
                ('email', models.CharField(verbose_name='იმეილი')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(related_query_name='blog', to='blog.author', verbose_name='ავტორი'),
        ),
    ]
