# Generated by Django 5.2.6 on 2025-09-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_author_remove_blog_author_blog_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.CharField(max_length=100, null=True, verbose_name='birth date'),
        ),
    ]
