# Generated by Django 5.2.6 on 2025-09-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_author_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
