# Generated by Django 5.2.6 on 2025-09-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_options_blog_order_blogimage_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'ordering': ['order'], 'verbose_name': 'Blog Image', 'verbose_name_plural': 'Blog Images'},
        ),
    ]
